// <auto-generated />
namespace fantasy_backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class criandoastables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(criandoastables));
        
        string IMigrationMetadata.Id
        {
            get { return "201803090105551_criando-as-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
